on:
  issues:
    types:
      - opened
      - labeled

permissions:
  issues: write

## MS:, SEV:, Fr:, To:は設定されていることを確認する

jobs:
  check-issue-labels:
    runs-on: ubuntu-latest
    steps:
      - id: labels
        if: |
          !contains(github.event.issue.labels.*.name, 'MS:')  ||
          !contains(github.event.issue.labels.*.name, 'SEV:') ||
          !contains(github.event.issue.labels.*.name, 'Fr:')  ||
          !contains(github.event.issue.labels.*.name, 'To:')
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment "$ISSUE_NUMBER" -b 'Missing labels `MS:`, `SEV:`, `Fr:`, or `To:`'

